parser: babel-eslint

plugins:
  - jest

extends:
  - eslint:recommended
  - plugin:jest/recommended

env:
  browser: true
  node: true
  es6: true
  jest: true

rules:
  semi:
    - error
    - never
  curly:
    - error
  no-var:
    - error
  comma-dangle:
    - error
    - always-multiline
  quotes:
    - error
    - single
  no-console:
    - off
  no-debugger:
    - off
  no-unused-vars:
    - error
  eol-last:
    - error
    - always
  jest/no-test-callback:
    - off
